# Generated by Django 4.0.4 on 2022-04-26 20:54

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carousels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='app/static/app/media'), upload_to='', verbose_name='image')),
            ],
            options={
                'verbose_name': 'carpusels in the main page',
                'verbose_name_plural': 'carousel',
            },
        ),
        migrations.CreateModel(
            name='categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'categories for nav items',
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('image', models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='app/static/app/media'), upload_to='', verbose_name='photo')),
                ('created', models.DateTimeField(auto_now=True)),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.categories', verbose_name='categories')),
            ],
            options={
                'verbose_name': 'products for the main page',
                'verbose_name_plural': 'products',
            },
        ),
    ]
