# Generated by Django 4.0.4 on 2022-04-27 20:35

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_carousels_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'delivery data',
                'verbose_name_plural': 'delivery info',
            },
        ),
        migrations.AddField(
            model_name='products',
            name='image1',
            field=models.ImageField(null=True, storage=django.core.files.storage.FileSystemStorage(location='app/static/app/media'), upload_to='', verbose_name='photo'),
        ),
    ]
