# Generated by Django 4.0.4 on 2022-04-27 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_delivery_products_image1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='image1',
        ),
    ]
