# Generated by Django 4.0.4 on 2022-04-28 08:37

from django.db import migrations
import faicon.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_products_image1'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='icon',
            field=faicon.fields.FAIconField(max_length=50, null=True),
        ),
    ]
