# Generated by Django 4.0.4 on 2022-04-28 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_delivery_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='icon',
        ),
        migrations.AlterField(
            model_name='delivery',
            name='text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
